[package]
name = "huaga"
version = "0.1.0"
authors = ["Kyle Zentner <zentner.kyle@gmail.com>"]

[dependencies]
glib = "0.0.8"
gdk = "0.3.0"
gdk-pixbuf = "0.0.1"
cairo-rs = "0.0.8"

[dependencies.gtk]
version = "0.0.7"
features = ["v3_10"]
